# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from fastmeow._generated.fastmeow.v1 import gateway_pb2 as fastmeow_dot_v1_dot_gateway__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in fastmeow/v1/gateway_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class GatewayServiceStub(object):
    """─────────────────────────────────────────────────────────────────────────────
    Service
    ─────────────────────────────────────────────────────────────────────────────

    Convention: every RPC has a dedicated *Response message even when the body
    is currently empty or trivial. This lets us add response fields later
    without breaking the wire.

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Ping = channel.unary_unary(
                '/fastmeow.v1.GatewayService/Ping',
                request_serializer=fastmeow_dot_v1_dot_gateway__pb2.PingRequest.SerializeToString,
                response_deserializer=fastmeow_dot_v1_dot_gateway__pb2.PingResponse.FromString,
                _registered_method=True)
        self.EnsureAccount = channel.unary_unary(
                '/fastmeow.v1.GatewayService/EnsureAccount',
                request_serializer=fastmeow_dot_v1_dot_gateway__pb2.EnsureAccountRequest.SerializeToString,
                response_deserializer=fastmeow_dot_v1_dot_gateway__pb2.EnsureAccountResponse.FromString,
                _registered_method=True)
        self.Connect = channel.unary_unary(
                '/fastmeow.v1.GatewayService/Connect',
                request_serializer=fastmeow_dot_v1_dot_gateway__pb2.ConnectRequest.SerializeToString,
                response_deserializer=fastmeow_dot_v1_dot_gateway__pb2.ConnectResponse.FromString,
                _registered_method=True)
        self.Disconnect = channel.unary_unary(
                '/fastmeow.v1.GatewayService/Disconnect',
                request_serializer=fastmeow_dot_v1_dot_gateway__pb2.DisconnectRequest.SerializeToString,
                response_deserializer=fastmeow_dot_v1_dot_gateway__pb2.DisconnectResponse.FromString,
                _registered_method=True)
        self.Logout = channel.unary_unary(
                '/fastmeow.v1.GatewayService/Logout',
                request_serializer=fastmeow_dot_v1_dot_gateway__pb2.LogoutRequest.SerializeToString,
                response_deserializer=fastmeow_dot_v1_dot_gateway__pb2.LogoutResponse.FromString,
                _registered_method=True)
        self.SendMessage = channel.unary_unary(
                '/fastmeow.v1.GatewayService/SendMessage',
                request_serializer=fastmeow_dot_v1_dot_gateway__pb2.SendMessageRequest.SerializeToString,
                response_deserializer=fastmeow_dot_v1_dot_gateway__pb2.SendMessageResponse.FromString,
                _registered_method=True)
        self.StreamEvents = channel.unary_stream(
                '/fastmeow.v1.GatewayService/StreamEvents',
                request_serializer=fastmeow_dot_v1_dot_gateway__pb2.StreamEventsRequest.SerializeToString,
                response_deserializer=fastmeow_dot_v1_dot_gateway__pb2.StreamEventsResponse.FromString,
                _registered_method=True)
        self.Shutdown = channel.unary_unary(
                '/fastmeow.v1.GatewayService/Shutdown',
                request_serializer=fastmeow_dot_v1_dot_gateway__pb2.ShutdownRequest.SerializeToString,
                response_deserializer=fastmeow_dot_v1_dot_gateway__pb2.ShutdownResponse.FromString,
                _registered_method=True)


class GatewayServiceServicer(object):
    """─────────────────────────────────────────────────────────────────────────────
    Service
    ─────────────────────────────────────────────────────────────────────────────

    Convention: every RPC has a dedicated *Response message even when the body
    is currently empty or trivial. This lets us add response fields later
    without breaking the wire.

    """

    def Ping(self, request, context):
        """Health & version handshake. Called by the supervisor right after spawn to
        verify the sidecar is alive and protocol-compatible.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def EnsureAccount(self, request, context):
        """Idempotently register an account_key with the sidecar. If the key is new,
        a fresh whatsmeow Device is created (unpaired). If it exists, the existing
        device is returned. Must be called before Connect.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Connect(self, request, context):
        """Drive the whatsmeow.Client lifecycle: open WebSocket, drive QR loop if
        unpaired, transition to CONNECTED on PairSuccess. Idempotent.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Disconnect(self, request, context):
        """Close the WebSocket but keep the device credentials.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Logout(self, request, context):
        """Wipe device credentials. Account must re-pair via QR after this.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SendMessage(self, request, context):
        """Send a message. The client_msg_id field provides idempotency; if a
        request with the same (account_key, client_msg_id) was acknowledged in
        the dedup window, the cached response is returned without resending.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StreamEvents(self, request, context):
        """Single long-lived server-stream carrying ALL events for ALL accounts on
        this sidecar. Python opens exactly one StreamEvents call per sidecar.
        Events from different accounts are multiplexed; consumers route by
        account_key.

        Ordering: events for a given (account_key, chat_jid) pair are emitted in
        monotonically-increasing seq order. Cross-chat ordering is not guaranteed.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Shutdown(self, request, context):
        """Request graceful shutdown. The sidecar will:
        1. Stop accepting new RPCs.
        2. Disconnect all clients cleanly.
        3. Flush event stream.
        4. Exit with code 0.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_GatewayServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Ping': grpc.unary_unary_rpc_method_handler(
                    servicer.Ping,
                    request_deserializer=fastmeow_dot_v1_dot_gateway__pb2.PingRequest.FromString,
                    response_serializer=fastmeow_dot_v1_dot_gateway__pb2.PingResponse.SerializeToString,
            ),
            'EnsureAccount': grpc.unary_unary_rpc_method_handler(
                    servicer.EnsureAccount,
                    request_deserializer=fastmeow_dot_v1_dot_gateway__pb2.EnsureAccountRequest.FromString,
                    response_serializer=fastmeow_dot_v1_dot_gateway__pb2.EnsureAccountResponse.SerializeToString,
            ),
            'Connect': grpc.unary_unary_rpc_method_handler(
                    servicer.Connect,
                    request_deserializer=fastmeow_dot_v1_dot_gateway__pb2.ConnectRequest.FromString,
                    response_serializer=fastmeow_dot_v1_dot_gateway__pb2.ConnectResponse.SerializeToString,
            ),
            'Disconnect': grpc.unary_unary_rpc_method_handler(
                    servicer.Disconnect,
                    request_deserializer=fastmeow_dot_v1_dot_gateway__pb2.DisconnectRequest.FromString,
                    response_serializer=fastmeow_dot_v1_dot_gateway__pb2.DisconnectResponse.SerializeToString,
            ),
            'Logout': grpc.unary_unary_rpc_method_handler(
                    servicer.Logout,
                    request_deserializer=fastmeow_dot_v1_dot_gateway__pb2.LogoutRequest.FromString,
                    response_serializer=fastmeow_dot_v1_dot_gateway__pb2.LogoutResponse.SerializeToString,
            ),
            'SendMessage': grpc.unary_unary_rpc_method_handler(
                    servicer.SendMessage,
                    request_deserializer=fastmeow_dot_v1_dot_gateway__pb2.SendMessageRequest.FromString,
                    response_serializer=fastmeow_dot_v1_dot_gateway__pb2.SendMessageResponse.SerializeToString,
            ),
            'StreamEvents': grpc.unary_stream_rpc_method_handler(
                    servicer.StreamEvents,
                    request_deserializer=fastmeow_dot_v1_dot_gateway__pb2.StreamEventsRequest.FromString,
                    response_serializer=fastmeow_dot_v1_dot_gateway__pb2.StreamEventsResponse.SerializeToString,
            ),
            'Shutdown': grpc.unary_unary_rpc_method_handler(
                    servicer.Shutdown,
                    request_deserializer=fastmeow_dot_v1_dot_gateway__pb2.ShutdownRequest.FromString,
                    response_serializer=fastmeow_dot_v1_dot_gateway__pb2.ShutdownResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'fastmeow.v1.GatewayService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('fastmeow.v1.GatewayService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class GatewayService(object):
    """─────────────────────────────────────────────────────────────────────────────
    Service
    ─────────────────────────────────────────────────────────────────────────────

    Convention: every RPC has a dedicated *Response message even when the body
    is currently empty or trivial. This lets us add response fields later
    without breaking the wire.

    """

    @staticmethod
    def Ping(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/fastmeow.v1.GatewayService/Ping',
            fastmeow_dot_v1_dot_gateway__pb2.PingRequest.SerializeToString,
            fastmeow_dot_v1_dot_gateway__pb2.PingResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def EnsureAccount(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/fastmeow.v1.GatewayService/EnsureAccount',
            fastmeow_dot_v1_dot_gateway__pb2.EnsureAccountRequest.SerializeToString,
            fastmeow_dot_v1_dot_gateway__pb2.EnsureAccountResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Connect(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/fastmeow.v1.GatewayService/Connect',
            fastmeow_dot_v1_dot_gateway__pb2.ConnectRequest.SerializeToString,
            fastmeow_dot_v1_dot_gateway__pb2.ConnectResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Disconnect(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/fastmeow.v1.GatewayService/Disconnect',
            fastmeow_dot_v1_dot_gateway__pb2.DisconnectRequest.SerializeToString,
            fastmeow_dot_v1_dot_gateway__pb2.DisconnectResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Logout(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/fastmeow.v1.GatewayService/Logout',
            fastmeow_dot_v1_dot_gateway__pb2.LogoutRequest.SerializeToString,
            fastmeow_dot_v1_dot_gateway__pb2.LogoutResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SendMessage(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/fastmeow.v1.GatewayService/SendMessage',
            fastmeow_dot_v1_dot_gateway__pb2.SendMessageRequest.SerializeToString,
            fastmeow_dot_v1_dot_gateway__pb2.SendMessageResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StreamEvents(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/fastmeow.v1.GatewayService/StreamEvents',
            fastmeow_dot_v1_dot_gateway__pb2.StreamEventsRequest.SerializeToString,
            fastmeow_dot_v1_dot_gateway__pb2.StreamEventsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Shutdown(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/fastmeow.v1.GatewayService/Shutdown',
            fastmeow_dot_v1_dot_gateway__pb2.ShutdownRequest.SerializeToString,
            fastmeow_dot_v1_dot_gateway__pb2.ShutdownResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
