# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from fastmeow._generated.fastmeow.v1 import gateway_pb2 as fastmeow_dot_v1_dot_gateway__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in fastmeow/v1/gateway_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class GatewayServiceStub(object):
    """─────────────────────────────────────────────────────────────────────────────
    Service (服务)
    ─────────────────────────────────────────────────────────────────────────────

    惯例：即使包体目前为空或微不足道，每个 RPC 也有专用的 *Response 消息。
    这让我们以后可以在不破坏 wire 协议的情况下添加响应字段。

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Ping = channel.unary_unary(
                '/fastmeow.v1.GatewayService/Ping',
                request_serializer=fastmeow_dot_v1_dot_gateway__pb2.PingRequest.SerializeToString,
                response_deserializer=fastmeow_dot_v1_dot_gateway__pb2.PingResponse.FromString,
                _registered_method=True)
        self.EnsureAccount = channel.unary_unary(
                '/fastmeow.v1.GatewayService/EnsureAccount',
                request_serializer=fastmeow_dot_v1_dot_gateway__pb2.EnsureAccountRequest.SerializeToString,
                response_deserializer=fastmeow_dot_v1_dot_gateway__pb2.EnsureAccountResponse.FromString,
                _registered_method=True)
        self.Connect = channel.unary_unary(
                '/fastmeow.v1.GatewayService/Connect',
                request_serializer=fastmeow_dot_v1_dot_gateway__pb2.ConnectRequest.SerializeToString,
                response_deserializer=fastmeow_dot_v1_dot_gateway__pb2.ConnectResponse.FromString,
                _registered_method=True)
        self.Disconnect = channel.unary_unary(
                '/fastmeow.v1.GatewayService/Disconnect',
                request_serializer=fastmeow_dot_v1_dot_gateway__pb2.DisconnectRequest.SerializeToString,
                response_deserializer=fastmeow_dot_v1_dot_gateway__pb2.DisconnectResponse.FromString,
                _registered_method=True)
        self.Logout = channel.unary_unary(
                '/fastmeow.v1.GatewayService/Logout',
                request_serializer=fastmeow_dot_v1_dot_gateway__pb2.LogoutRequest.SerializeToString,
                response_deserializer=fastmeow_dot_v1_dot_gateway__pb2.LogoutResponse.FromString,
                _registered_method=True)
        self.SendMessage = channel.unary_unary(
                '/fastmeow.v1.GatewayService/SendMessage',
                request_serializer=fastmeow_dot_v1_dot_gateway__pb2.SendMessageRequest.SerializeToString,
                response_deserializer=fastmeow_dot_v1_dot_gateway__pb2.SendMessageResponse.FromString,
                _registered_method=True)
        self.StreamEvents = channel.unary_stream(
                '/fastmeow.v1.GatewayService/StreamEvents',
                request_serializer=fastmeow_dot_v1_dot_gateway__pb2.StreamEventsRequest.SerializeToString,
                response_deserializer=fastmeow_dot_v1_dot_gateway__pb2.StreamEventsResponse.FromString,
                _registered_method=True)
        self.ListJoinedGroups = channel.unary_unary(
                '/fastmeow.v1.GatewayService/ListJoinedGroups',
                request_serializer=fastmeow_dot_v1_dot_gateway__pb2.ListJoinedGroupsRequest.SerializeToString,
                response_deserializer=fastmeow_dot_v1_dot_gateway__pb2.ListJoinedGroupsResponse.FromString,
                _registered_method=True)
        self.GetGroupInfo = channel.unary_unary(
                '/fastmeow.v1.GatewayService/GetGroupInfo',
                request_serializer=fastmeow_dot_v1_dot_gateway__pb2.GetGroupInfoRequest.SerializeToString,
                response_deserializer=fastmeow_dot_v1_dot_gateway__pb2.GetGroupInfoResponse.FromString,
                _registered_method=True)
        self.PreviewGroupInvite = channel.unary_unary(
                '/fastmeow.v1.GatewayService/PreviewGroupInvite',
                request_serializer=fastmeow_dot_v1_dot_gateway__pb2.PreviewGroupInviteRequest.SerializeToString,
                response_deserializer=fastmeow_dot_v1_dot_gateway__pb2.PreviewGroupInviteResponse.FromString,
                _registered_method=True)
        self.JoinGroupViaInvite = channel.unary_unary(
                '/fastmeow.v1.GatewayService/JoinGroupViaInvite',
                request_serializer=fastmeow_dot_v1_dot_gateway__pb2.JoinGroupViaInviteRequest.SerializeToString,
                response_deserializer=fastmeow_dot_v1_dot_gateway__pb2.JoinGroupViaInviteResponse.FromString,
                _registered_method=True)
        self.LeaveGroup = channel.unary_unary(
                '/fastmeow.v1.GatewayService/LeaveGroup',
                request_serializer=fastmeow_dot_v1_dot_gateway__pb2.LeaveGroupRequest.SerializeToString,
                response_deserializer=fastmeow_dot_v1_dot_gateway__pb2.LeaveGroupResponse.FromString,
                _registered_method=True)
        self.CreateGroup = channel.unary_unary(
                '/fastmeow.v1.GatewayService/CreateGroup',
                request_serializer=fastmeow_dot_v1_dot_gateway__pb2.CreateGroupRequest.SerializeToString,
                response_deserializer=fastmeow_dot_v1_dot_gateway__pb2.CreateGroupResponse.FromString,
                _registered_method=True)
        self.UpdateGroupSettings = channel.unary_unary(
                '/fastmeow.v1.GatewayService/UpdateGroupSettings',
                request_serializer=fastmeow_dot_v1_dot_gateway__pb2.UpdateGroupSettingsRequest.SerializeToString,
                response_deserializer=fastmeow_dot_v1_dot_gateway__pb2.UpdateGroupSettingsResponse.FromString,
                _registered_method=True)
        self.UpdateGroupParticipants = channel.unary_unary(
                '/fastmeow.v1.GatewayService/UpdateGroupParticipants',
                request_serializer=fastmeow_dot_v1_dot_gateway__pb2.UpdateGroupParticipantsRequest.SerializeToString,
                response_deserializer=fastmeow_dot_v1_dot_gateway__pb2.UpdateGroupParticipantsResponse.FromString,
                _registered_method=True)
        self.GetGroupInviteLink = channel.unary_unary(
                '/fastmeow.v1.GatewayService/GetGroupInviteLink',
                request_serializer=fastmeow_dot_v1_dot_gateway__pb2.GetGroupInviteLinkRequest.SerializeToString,
                response_deserializer=fastmeow_dot_v1_dot_gateway__pb2.GetGroupInviteLinkResponse.FromString,
                _registered_method=True)
        self.MarkRead = channel.unary_unary(
                '/fastmeow.v1.GatewayService/MarkRead',
                request_serializer=fastmeow_dot_v1_dot_gateway__pb2.MarkReadRequest.SerializeToString,
                response_deserializer=fastmeow_dot_v1_dot_gateway__pb2.MarkReadResponse.FromString,
                _registered_method=True)
        self.SendPresence = channel.unary_unary(
                '/fastmeow.v1.GatewayService/SendPresence',
                request_serializer=fastmeow_dot_v1_dot_gateway__pb2.SendPresenceRequest.SerializeToString,
                response_deserializer=fastmeow_dot_v1_dot_gateway__pb2.SendPresenceResponse.FromString,
                _registered_method=True)
        self.SendChatPresence = channel.unary_unary(
                '/fastmeow.v1.GatewayService/SendChatPresence',
                request_serializer=fastmeow_dot_v1_dot_gateway__pb2.SendChatPresenceRequest.SerializeToString,
                response_deserializer=fastmeow_dot_v1_dot_gateway__pb2.SendChatPresenceResponse.FromString,
                _registered_method=True)
        self.SubscribePresence = channel.unary_unary(
                '/fastmeow.v1.GatewayService/SubscribePresence',
                request_serializer=fastmeow_dot_v1_dot_gateway__pb2.SubscribePresenceRequest.SerializeToString,
                response_deserializer=fastmeow_dot_v1_dot_gateway__pb2.SubscribePresenceResponse.FromString,
                _registered_method=True)
        self.Shutdown = channel.unary_unary(
                '/fastmeow.v1.GatewayService/Shutdown',
                request_serializer=fastmeow_dot_v1_dot_gateway__pb2.ShutdownRequest.SerializeToString,
                response_deserializer=fastmeow_dot_v1_dot_gateway__pb2.ShutdownResponse.FromString,
                _registered_method=True)


class GatewayServiceServicer(object):
    """─────────────────────────────────────────────────────────────────────────────
    Service (服务)
    ─────────────────────────────────────────────────────────────────────────────

    惯例：即使包体目前为空或微不足道，每个 RPC 也有专用的 *Response 消息。
    这让我们以后可以在不破坏 wire 协议的情况下添加响应字段。

    """

    def Ping(self, request, context):
        """健康检查与版本握手。由 supervisor 在启动后立即调用，
        以验证 sidecar 是否存活且协议兼容。
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def EnsureAccount(self, request, context):
        """幂等地向 sidecar 注册 账号 / account_key。如果 key 是新的，
        则创建一个新的 whatsmeow 设备（未配对）。如果已存在，
        则返回现有设备。必须在 Connect 之前调用。
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Connect(self, request, context):
        """驱动 whatsmeow.Client 生命周期：打开 WebSocket，如果是
        未配对状态则驱动 QR 循环，在 PairSuccess 时转换到 CONNECTED 状态。幂等。
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Disconnect(self, request, context):
        """关闭 WebSocket 但保留设备凭据。
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Logout(self, request, context):
        """清除设备凭据。此后账号必须通过 QR 重新配对。
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SendMessage(self, request, context):
        """发送消息。client_msg_id 字段提供幂等性；如果具有相同
        (account_key, client_msg_id) 的请求在去重窗口内已被确认，
        则返回缓存的响应而不重新发送。
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StreamEvents(self, request, context):
        """单个长连接服务端流，承载此 sidecar 上所有账号的所有事件。
        Python 为每个 sidecar 打开一个 StreamEvents 调用。
        来自不同账号的事件被多路复用；消费者通过 account_key 进行路由。

        顺序：给定 (account_key, chat_jid) 对的事件按单调递增的 seq 顺序发出。
        不保证跨聊天顺序。
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListJoinedGroups(self, request, context):
        """───────────────────────────────────────────────────────────────────────────
        Group RPCs (Phase 4.1)
        ───────────────────────────────────────────────────────────────────────────

        设计要点：
        - 所有读 RPC 直接命中 whatsmeow 的本地缓存或服务端拉取，sidecar 不缓存。
        - 所有写 RPC 由用户主动触发，不做幂等键去重（与 SendMessage 不同）；
        重复调用会向 WhatsApp 重复发送，由调用方负责。
        - 错误映射：JID 非法 → INVALID_ARGUMENT；账号未连接 → FAILED_PRECONDITION；
        whatsmeow 业务错误（403/不在群里/被踢等）→ PERMISSION_DENIED 或 NOT_FOUND；
        其他网络/服务端错误 → UNAVAILABLE 并附带原始错误文本。

        列出该账号当前加入的所有群（whatsmeow GetJoinedGroups）。
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetGroupInfo(self, request, context):
        """获取单个群的完整元数据（whatsmeow GetGroupInfo）。
        如果账号不在该群，返回 NOT_FOUND。
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PreviewGroupInvite(self, request, context):
        """通过邀请链接预览群信息但不加入（whatsmeow GetGroupInfoFromLink）。
        邀请链接形如 "https://chat.whatsapp.com/<code>"，code 部分会被自动剥取。
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def JoinGroupViaInvite(self, request, context):
        """通过邀请链接加入群（whatsmeow JoinGroupWithLink）。
        加入后 whatsmeow 会发出 GroupInfo 事件，由 bus 转发为 JoinedGroupEvent。
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def LeaveGroup(self, request, context):
        """离开群（whatsmeow LeaveGroup）。如果账号不在群里，返回 NOT_FOUND。
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateGroup(self, request, context):
        """创建新群（whatsmeow CreateGroup）。
        至少需要一个除创建者外的初始参与者；whatsmeow 不允许创建只有自己的群。
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateGroupSettings(self, request, context):
        """修改群设置（名称/主题/announce/locked）。
        仅允许修改请求中显式设置的字段，缺省字段保持不变。
        各字段对应 whatsmeow 的 SetGroupName / SetGroupTopic /
        SetGroupAnnounce / SetGroupLocked。需要管理员权限。
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateGroupParticipants(self, request, context):
        """添加 / 移除 / 提升 / 降级群成员（whatsmeow UpdateGroupParticipants）。
        单次调用所有目标 JID 共享同一动作；混合动作请发起多次调用。
        需要管理员权限。
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetGroupInviteLink(self, request, context):
        """取回当前群的邀请链接（whatsmeow GetGroupInviteLink）。
        reset=true 时会失效旧链接并生成新链接。需要管理员权限。
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def MarkRead(self, request, context):
        """───────────────────────────────────────────────────────────────────────────
        Receipts & Presence (Phase 4.2)
        ───────────────────────────────────────────────────────────────────────────

        将一组消息标记为已读 / 已播放。对应 whatsmeow Client.MarkRead。
        sender_jid 在 DM 中等于 chat_jid，在群聊中是真正发送者的 JID。
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SendPresence(self, request, context):
        """推送账号自身的全局在线状态（available / unavailable）。
        对应 whatsmeow Client.SendPresence。
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SendChatPresence(self, request, context):
        """在指定会话内推送 typing / paused 等输入状态。
        对应 whatsmeow Client.SendChatPresence。
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SubscribePresence(self, request, context):
        """订阅指定 JID 的在线状态推送（对方上线 / 下线 / 最近一次活跃时间）。
        对应 whatsmeow Client.SubscribePresence。
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Shutdown(self, request, context):
        """请求优雅停机。sidecar 将：
        1. 停止接受新的 RPC。
        2. 干净地断开所有客户端连接。
        3. 刷新事件流。
        4. 以代码 0 退出。
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_GatewayServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Ping': grpc.unary_unary_rpc_method_handler(
                    servicer.Ping,
                    request_deserializer=fastmeow_dot_v1_dot_gateway__pb2.PingRequest.FromString,
                    response_serializer=fastmeow_dot_v1_dot_gateway__pb2.PingResponse.SerializeToString,
            ),
            'EnsureAccount': grpc.unary_unary_rpc_method_handler(
                    servicer.EnsureAccount,
                    request_deserializer=fastmeow_dot_v1_dot_gateway__pb2.EnsureAccountRequest.FromString,
                    response_serializer=fastmeow_dot_v1_dot_gateway__pb2.EnsureAccountResponse.SerializeToString,
            ),
            'Connect': grpc.unary_unary_rpc_method_handler(
                    servicer.Connect,
                    request_deserializer=fastmeow_dot_v1_dot_gateway__pb2.ConnectRequest.FromString,
                    response_serializer=fastmeow_dot_v1_dot_gateway__pb2.ConnectResponse.SerializeToString,
            ),
            'Disconnect': grpc.unary_unary_rpc_method_handler(
                    servicer.Disconnect,
                    request_deserializer=fastmeow_dot_v1_dot_gateway__pb2.DisconnectRequest.FromString,
                    response_serializer=fastmeow_dot_v1_dot_gateway__pb2.DisconnectResponse.SerializeToString,
            ),
            'Logout': grpc.unary_unary_rpc_method_handler(
                    servicer.Logout,
                    request_deserializer=fastmeow_dot_v1_dot_gateway__pb2.LogoutRequest.FromString,
                    response_serializer=fastmeow_dot_v1_dot_gateway__pb2.LogoutResponse.SerializeToString,
            ),
            'SendMessage': grpc.unary_unary_rpc_method_handler(
                    servicer.SendMessage,
                    request_deserializer=fastmeow_dot_v1_dot_gateway__pb2.SendMessageRequest.FromString,
                    response_serializer=fastmeow_dot_v1_dot_gateway__pb2.SendMessageResponse.SerializeToString,
            ),
            'StreamEvents': grpc.unary_stream_rpc_method_handler(
                    servicer.StreamEvents,
                    request_deserializer=fastmeow_dot_v1_dot_gateway__pb2.StreamEventsRequest.FromString,
                    response_serializer=fastmeow_dot_v1_dot_gateway__pb2.StreamEventsResponse.SerializeToString,
            ),
            'ListJoinedGroups': grpc.unary_unary_rpc_method_handler(
                    servicer.ListJoinedGroups,
                    request_deserializer=fastmeow_dot_v1_dot_gateway__pb2.ListJoinedGroupsRequest.FromString,
                    response_serializer=fastmeow_dot_v1_dot_gateway__pb2.ListJoinedGroupsResponse.SerializeToString,
            ),
            'GetGroupInfo': grpc.unary_unary_rpc_method_handler(
                    servicer.GetGroupInfo,
                    request_deserializer=fastmeow_dot_v1_dot_gateway__pb2.GetGroupInfoRequest.FromString,
                    response_serializer=fastmeow_dot_v1_dot_gateway__pb2.GetGroupInfoResponse.SerializeToString,
            ),
            'PreviewGroupInvite': grpc.unary_unary_rpc_method_handler(
                    servicer.PreviewGroupInvite,
                    request_deserializer=fastmeow_dot_v1_dot_gateway__pb2.PreviewGroupInviteRequest.FromString,
                    response_serializer=fastmeow_dot_v1_dot_gateway__pb2.PreviewGroupInviteResponse.SerializeToString,
            ),
            'JoinGroupViaInvite': grpc.unary_unary_rpc_method_handler(
                    servicer.JoinGroupViaInvite,
                    request_deserializer=fastmeow_dot_v1_dot_gateway__pb2.JoinGroupViaInviteRequest.FromString,
                    response_serializer=fastmeow_dot_v1_dot_gateway__pb2.JoinGroupViaInviteResponse.SerializeToString,
            ),
            'LeaveGroup': grpc.unary_unary_rpc_method_handler(
                    servicer.LeaveGroup,
                    request_deserializer=fastmeow_dot_v1_dot_gateway__pb2.LeaveGroupRequest.FromString,
                    response_serializer=fastmeow_dot_v1_dot_gateway__pb2.LeaveGroupResponse.SerializeToString,
            ),
            'CreateGroup': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateGroup,
                    request_deserializer=fastmeow_dot_v1_dot_gateway__pb2.CreateGroupRequest.FromString,
                    response_serializer=fastmeow_dot_v1_dot_gateway__pb2.CreateGroupResponse.SerializeToString,
            ),
            'UpdateGroupSettings': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateGroupSettings,
                    request_deserializer=fastmeow_dot_v1_dot_gateway__pb2.UpdateGroupSettingsRequest.FromString,
                    response_serializer=fastmeow_dot_v1_dot_gateway__pb2.UpdateGroupSettingsResponse.SerializeToString,
            ),
            'UpdateGroupParticipants': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateGroupParticipants,
                    request_deserializer=fastmeow_dot_v1_dot_gateway__pb2.UpdateGroupParticipantsRequest.FromString,
                    response_serializer=fastmeow_dot_v1_dot_gateway__pb2.UpdateGroupParticipantsResponse.SerializeToString,
            ),
            'GetGroupInviteLink': grpc.unary_unary_rpc_method_handler(
                    servicer.GetGroupInviteLink,
                    request_deserializer=fastmeow_dot_v1_dot_gateway__pb2.GetGroupInviteLinkRequest.FromString,
                    response_serializer=fastmeow_dot_v1_dot_gateway__pb2.GetGroupInviteLinkResponse.SerializeToString,
            ),
            'MarkRead': grpc.unary_unary_rpc_method_handler(
                    servicer.MarkRead,
                    request_deserializer=fastmeow_dot_v1_dot_gateway__pb2.MarkReadRequest.FromString,
                    response_serializer=fastmeow_dot_v1_dot_gateway__pb2.MarkReadResponse.SerializeToString,
            ),
            'SendPresence': grpc.unary_unary_rpc_method_handler(
                    servicer.SendPresence,
                    request_deserializer=fastmeow_dot_v1_dot_gateway__pb2.SendPresenceRequest.FromString,
                    response_serializer=fastmeow_dot_v1_dot_gateway__pb2.SendPresenceResponse.SerializeToString,
            ),
            'SendChatPresence': grpc.unary_unary_rpc_method_handler(
                    servicer.SendChatPresence,
                    request_deserializer=fastmeow_dot_v1_dot_gateway__pb2.SendChatPresenceRequest.FromString,
                    response_serializer=fastmeow_dot_v1_dot_gateway__pb2.SendChatPresenceResponse.SerializeToString,
            ),
            'SubscribePresence': grpc.unary_unary_rpc_method_handler(
                    servicer.SubscribePresence,
                    request_deserializer=fastmeow_dot_v1_dot_gateway__pb2.SubscribePresenceRequest.FromString,
                    response_serializer=fastmeow_dot_v1_dot_gateway__pb2.SubscribePresenceResponse.SerializeToString,
            ),
            'Shutdown': grpc.unary_unary_rpc_method_handler(
                    servicer.Shutdown,
                    request_deserializer=fastmeow_dot_v1_dot_gateway__pb2.ShutdownRequest.FromString,
                    response_serializer=fastmeow_dot_v1_dot_gateway__pb2.ShutdownResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'fastmeow.v1.GatewayService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('fastmeow.v1.GatewayService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class GatewayService(object):
    """─────────────────────────────────────────────────────────────────────────────
    Service (服务)
    ─────────────────────────────────────────────────────────────────────────────

    惯例：即使包体目前为空或微不足道，每个 RPC 也有专用的 *Response 消息。
    这让我们以后可以在不破坏 wire 协议的情况下添加响应字段。

    """

    @staticmethod
    def Ping(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/fastmeow.v1.GatewayService/Ping',
            fastmeow_dot_v1_dot_gateway__pb2.PingRequest.SerializeToString,
            fastmeow_dot_v1_dot_gateway__pb2.PingResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def EnsureAccount(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/fastmeow.v1.GatewayService/EnsureAccount',
            fastmeow_dot_v1_dot_gateway__pb2.EnsureAccountRequest.SerializeToString,
            fastmeow_dot_v1_dot_gateway__pb2.EnsureAccountResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Connect(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/fastmeow.v1.GatewayService/Connect',
            fastmeow_dot_v1_dot_gateway__pb2.ConnectRequest.SerializeToString,
            fastmeow_dot_v1_dot_gateway__pb2.ConnectResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Disconnect(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/fastmeow.v1.GatewayService/Disconnect',
            fastmeow_dot_v1_dot_gateway__pb2.DisconnectRequest.SerializeToString,
            fastmeow_dot_v1_dot_gateway__pb2.DisconnectResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Logout(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/fastmeow.v1.GatewayService/Logout',
            fastmeow_dot_v1_dot_gateway__pb2.LogoutRequest.SerializeToString,
            fastmeow_dot_v1_dot_gateway__pb2.LogoutResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SendMessage(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/fastmeow.v1.GatewayService/SendMessage',
            fastmeow_dot_v1_dot_gateway__pb2.SendMessageRequest.SerializeToString,
            fastmeow_dot_v1_dot_gateway__pb2.SendMessageResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StreamEvents(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/fastmeow.v1.GatewayService/StreamEvents',
            fastmeow_dot_v1_dot_gateway__pb2.StreamEventsRequest.SerializeToString,
            fastmeow_dot_v1_dot_gateway__pb2.StreamEventsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListJoinedGroups(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/fastmeow.v1.GatewayService/ListJoinedGroups',
            fastmeow_dot_v1_dot_gateway__pb2.ListJoinedGroupsRequest.SerializeToString,
            fastmeow_dot_v1_dot_gateway__pb2.ListJoinedGroupsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetGroupInfo(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/fastmeow.v1.GatewayService/GetGroupInfo',
            fastmeow_dot_v1_dot_gateway__pb2.GetGroupInfoRequest.SerializeToString,
            fastmeow_dot_v1_dot_gateway__pb2.GetGroupInfoResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def PreviewGroupInvite(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/fastmeow.v1.GatewayService/PreviewGroupInvite',
            fastmeow_dot_v1_dot_gateway__pb2.PreviewGroupInviteRequest.SerializeToString,
            fastmeow_dot_v1_dot_gateway__pb2.PreviewGroupInviteResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def JoinGroupViaInvite(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/fastmeow.v1.GatewayService/JoinGroupViaInvite',
            fastmeow_dot_v1_dot_gateway__pb2.JoinGroupViaInviteRequest.SerializeToString,
            fastmeow_dot_v1_dot_gateway__pb2.JoinGroupViaInviteResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def LeaveGroup(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/fastmeow.v1.GatewayService/LeaveGroup',
            fastmeow_dot_v1_dot_gateway__pb2.LeaveGroupRequest.SerializeToString,
            fastmeow_dot_v1_dot_gateway__pb2.LeaveGroupResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CreateGroup(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/fastmeow.v1.GatewayService/CreateGroup',
            fastmeow_dot_v1_dot_gateway__pb2.CreateGroupRequest.SerializeToString,
            fastmeow_dot_v1_dot_gateway__pb2.CreateGroupResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateGroupSettings(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/fastmeow.v1.GatewayService/UpdateGroupSettings',
            fastmeow_dot_v1_dot_gateway__pb2.UpdateGroupSettingsRequest.SerializeToString,
            fastmeow_dot_v1_dot_gateway__pb2.UpdateGroupSettingsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateGroupParticipants(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/fastmeow.v1.GatewayService/UpdateGroupParticipants',
            fastmeow_dot_v1_dot_gateway__pb2.UpdateGroupParticipantsRequest.SerializeToString,
            fastmeow_dot_v1_dot_gateway__pb2.UpdateGroupParticipantsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetGroupInviteLink(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/fastmeow.v1.GatewayService/GetGroupInviteLink',
            fastmeow_dot_v1_dot_gateway__pb2.GetGroupInviteLinkRequest.SerializeToString,
            fastmeow_dot_v1_dot_gateway__pb2.GetGroupInviteLinkResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def MarkRead(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/fastmeow.v1.GatewayService/MarkRead',
            fastmeow_dot_v1_dot_gateway__pb2.MarkReadRequest.SerializeToString,
            fastmeow_dot_v1_dot_gateway__pb2.MarkReadResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SendPresence(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/fastmeow.v1.GatewayService/SendPresence',
            fastmeow_dot_v1_dot_gateway__pb2.SendPresenceRequest.SerializeToString,
            fastmeow_dot_v1_dot_gateway__pb2.SendPresenceResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SendChatPresence(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/fastmeow.v1.GatewayService/SendChatPresence',
            fastmeow_dot_v1_dot_gateway__pb2.SendChatPresenceRequest.SerializeToString,
            fastmeow_dot_v1_dot_gateway__pb2.SendChatPresenceResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SubscribePresence(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/fastmeow.v1.GatewayService/SubscribePresence',
            fastmeow_dot_v1_dot_gateway__pb2.SubscribePresenceRequest.SerializeToString,
            fastmeow_dot_v1_dot_gateway__pb2.SubscribePresenceResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Shutdown(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/fastmeow.v1.GatewayService/Shutdown',
            fastmeow_dot_v1_dot_gateway__pb2.ShutdownRequest.SerializeToString,
            fastmeow_dot_v1_dot_gateway__pb2.ShutdownResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
